services:
  - type: web
    name: minio-mcp-server
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /mcp
    envVars:
      - key: MINIO_ENDPOINT
        sync: false
      - key: MINIO_PORT
        value: "443"
      - key: MINIO_USE_SSL
        value: "true"
      - key: MINIO_ACCESS_KEY
        sync: false
      - key: MINIO_SECRET_KEY
        sync: false
      - key: MINIO_BUCKET_NAME
        sync: false
